spring:
  application:
    name: yu-ai-agent
  profiles:
   active: local

server:
  address: 0.0.0.0
  port: 8105
  servlet:
    context-path: /api
    # cookie 30 \u5929\u8FC7\u671F
    session:
      cookie:
        max-age: 2592000
# \u63A5\u53E3\u6587\u6863\u914D\u7F6E
knife4j:
  enable: true
  openapi:
    title: "\u63A5\u53E3\u6587\u6863"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.fangjun.yuaiagent.controller
